name: Smartle Website update

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          scp -r ./* ${YOUR_USERNAME}@${YOUR_SERVER_IP}:/var/www/Smartle-website/
        env:
          YOUR_USERNAME: ${{ secrets.YOUR_USERNAME }}
          YOUR_SERVER_IP: ${{ secrets.YOUR_SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}

