name: Smartle Website update
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Server
        run: |
          rsync -avz --delete . ${SMARTLE_USERNAME}@${SMARTLE_SERVER_IP}:/var/www/Smartle-website/
        env:
          YOUR_USERNAME: ${{ secrets.SMARTLE_USERNAME }}
          YOUR_SERVER_IP: ${{ secrets.SMARTLE_SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SMART_SSH_PRIVATE_KEY}}
