name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run deployment script with sudo
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh -i deploy_key.pem root@3.85.202.239 "sudo bash -s" < /var/www/Smartle-website/hooks/post-receive

