name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run deployment script with sudo
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your_server "sudo bash -s" < /var/www/Smartle-website/hooks/post-receive

